$tops = [
  [
    '                                                                                                                                                    ',
    '                                                                                                       ..-uwZZZZZZZZZZZZXA+-..   ._```_-            ',
    '                                                                                                   .(wZZZZZZZZuZuZZZZZZZZZZZZZZGJ-      _           ',
    '                                                                                                .(XZZZZZZZZZZZZZZZuZZZZZZZZZZZZZZV`     _           ',
    '                                                                                              .JZZZZZZZZZuZZuZZuZZZZZuZZZZZZZZZZr``....-            ',
    '                                                                                             .XZu00000000XuZZZZZZZZuZZZZuZZuZZZ0`                   ',
    '                   .Jy0!       ..JwXl                                                       .<!_````````````_~<?7T4XZZZZZZZZuZu%                    ',
    '                  .yX=       .dyXY=!                                                       _`                      `_?7TXZZZZZZ!                    ',
    '                 .y0-.J&,   .yy$.....                                                     _`                            `~?4ZZC.--.---..            ',
    '                `dyyUY=!   .yyUUUUUUXXC                                                    _  ...._~~~~~__.....            `(=           `_.        ',
    '                 dZ) ..., .yy%                                                             ___(,......-gs..~~~~___~_..       _              _-      ',
    '                 dyyyXY7!.wyZyyyyyyX&                                                       ~_T5-____.-?:_~~:~~.....-_`__..  _                _.    ',
    '                 dy%     JZf`     ``                                                      _`   `_~~~_``       _~_~_~__     `_-.                __   ',
    '          ..((.. dyI+zlldy0<. ..(++++.                                                  _``                           __.      _.              _.   ',
    '          (lllttllllllllltllll<<<<<<<!                                                 _`                               __      _.              _   ',
    '            .lllllllllllllllllO+-``                                                    _.                                ~      .`             _    ',
    '           .tllltlltlllllllllllll:                                                      _.                               _      __             _    ',
    '           (llltllllltltlltlltlllO.                                                      _`                            ._         _           _`    ',
    '           lllllltllllllllllllllll~                                                     ._                            .`          ~          .`     ',
    '          .uyllllltlltlltlltlltlll!                                                      _                      ....-(_          `_ .(++++-. _`     ',
    '          ,M#lltlllllqNmllllllllll`                                                      _. `          ..     .(dZuZZZn-.        .(=======<<1       ',
    '         .JOOOlllltlldM8lltlltlzz<.                                                        `_-       .(J&J((JzXZZZZZZZZZXo_    .(==zsZ====<:+~      ',
    '        (ldppfIllllllllllllllz<~~~~                                                         .G----(J&NZZZZZZZZZZZZZuZZuZZZn-..(==uwZZk======v       ',
    '        .1lOOOlltlltlllltzz<~~~~~.~_                                                        JZZZZZXMMHZZZZZZZZuZZuZZZZZZu0VO===udZyZZyXAc<?`        ',
    '           ??<<<<<<<<?<<~~~~~.~.~~.~(z+(..........(.                                  ` ..((z=======lzzzzzzzzzzzz==========zusXZyZZyZZyV            ',
    '                      ~~~.~.~~.~~~(zll=dyZyyZyyZyk=lltz-..vlllz                    `..===1zuuwwwwwwwwwAAwsssssssOAwwwwwXZZZZZyZyZyZyZyX!            ',
    '                      _~.~~.~~~.(1llll=dZZZZZZZyZk=llllltz<~`                    `.(==uwZZyZZyZZZyZZyyZyZyZZZZyZyyZZZZZyZyyZyZZZyZZZyZ}             ',
    '                       ~~.~~._((llllll=zyyZyyZyZZ0========1......               `.==uXZZZyZZyZyZyZZyZZyZZyZyZyZZZyZyZZyZyZZyZyZyZyZyZf              ',
    '                         ~._-(llllllll==vVUUUUVVV1=llllllllv???<<<<1==l=++((....,==dZZZyZZyZZyZyZZyZZyZZyZZyZZyZyZZyyZyZZyZZyZyZZyZZf`              ',
    '                          .zlllllllltllllllllllllllllltllllz              `~!???==zZyZyZyZyZyZZZyZZyZZyZZyZZyZyZZyZZZyZyZZyZZyZZyZy0!               ',
  ],
  [
    '                                                                                                                                 ._```_-            ',
    '                                                                                                       ..-uwZZZZZZZZZZZZXA+-..   .      _           ',
    '                                                                                                   .(wZZZZZZZZuZuZZZZZZZZZZZZZZGJ-      _           ',
    '                                                                                                .(XZZZZZZZZZZZZZZZuZZZZZZZZZZZZZZV`....-            ',
    '                                                                                              .JZZZZZZZZZuZZuZZuZZZZZuZZZZZZZZZZr`                  ',
    '                                                                                             .XZu00000000XuZZZZZZZZuZZZZuZZuZZZ0`                   ',
    '                   .Jy0!       ..JwXl                                                       .<!_````````````_~<?7T4XZZZZZZZZuZu%                    ',
    '                  .yX=       .dyXY=!                                                       _`                      `_?7TXZZZZZZ!                    ',
    '                 .y0-.J&,   .yy$.....                                                     _`                            `~?4ZZC.--.---..            ',
    '                `dyyUY=!   .yyUUUUUUXXC                                                    _  ...._~~~~~__.....            `(=           `_.        ',
    '                 dZ) ..., .yy%                                                             ___(,......-gs..~~~~___~_..       _              _-      ',
    '                 dyyyXY7!.wyZyyyyyyX&                                                       ~_T5-____.-?:_~~:~~.....-_`__..  _                _.    ',
    '                 dy%     JZf`     ``                                                      _`   `_~~~_``       _~_~_~__     `_-.                __   ',
    '          ..((.. dyI+zlldy0<. ..(++++.                                                  _``                           __.      _.              _.   ',
    '          (lllttllllllllltllll<<<<<<<!                                                 _`                               __      _.             _    ',
    '            .lllllllllllllllllO+-``                                                    _.                                ~      .`             _    ',
    '           .tllltlltlllllllllllll:                                                      _.                               _      __             _    ',
    '           (llltllllltltlltlltlllO.                                                      _`                            ._         _           _`    ',
    '           lllllltllllllllllllllll~                                                     ._                            .`          ~          .`     ',
    '          .uyllllltlltlltlltlltlll!                                                      _                      ....-(_          `_ .(++++-. _`     ',
    '          ,M#lltlllllqNmllllllllll`                                                      _. `          ..     .(dZuZZZn-.        .(=======<<1       ',
    '         .JOOOlllltlldM8lltlltlzz<.                                                        `_-       .(J&J((JzXZZZZZZZZZXo_    .(==zsZ====<:+~      ',
    '        (ldppfIllllllllllllllz<~~~~                                                         .G----(J&NZZZZZZZZZZZZZuZZuZZZn-..(==uwZZk======v       ',
    '        .1lOOOlltlltlllltzz<~~~~~.~_                                                        JZZZZZXMMHZZZZZZZZuZZuZZZZZZu0VO===udZyZZyXAc<?`        ',
    '           ??<<<<<<<<?<<~~~~~.~.~~.~(z+(..........(.       -zz                        ` ..((z=======lzzzzzzzzzzzz==========zusXZyZZyZZyV            ',
    '                      ~~~.~.~~.~~~(zll=dyZyyZyyZyk=lltz-..Jll                      `..===1zuuwwwwwwwwwAAwsssssssOAwwwwwXZZZZZyZyZyZyZyX!            ',
    '                      _~.~~.~~~.(1llll=dZZZZZZZyZk=llllltz<~`                    `.(==uwZZyZZyZZZyZZyyZyZyZZZZyZyyZZZZZyZyyZyZZZyZZZyZ}             ',
    '                       ~~.~~._((llllll=zyyZyyZyZZ0========1......               `.==uXZZZyZZyZyZyZZyZZyZZyZyZyZZZyZyZZyZyZZyZyZyZyZyZf              ',
    '                         ~._-(llllllll==vVUUUUVVV1=llllllllv???<<<<1==l=++((....,==dZZZyZZyZZyZyZZyZZyZZyZZyZZyZyZZyyZyZZyZZyZyZZyZZf`              ',
    '                          .zlllllllltllllllllllllllllltllllz              `~!???==zZyZyZyZyZyZZZyZZyZZyZZyZZyZyZZyZZZyZyZZyZZyZZyZy0!               ',
  ],
  [
    '                                                                                                                                                    ',
    '                                                                                                       ..-uwZZZZZZZZZZZZXA+-..   ._```_-            ',
    '                                                                                                   .(wZZZZZZZZuZuZZZZZZZZZZZZZZGJ-      _           ',
    '                                                                                                .(XZZZZZZZZZZZZZZZuZZZZZZZZZZZZZZV`     _           ',
    '                                                                                              .JZZZZZZZZZuZZuZZuZZZZZuZZZZZZZZZZr``....-            ',
    '                                                                                             .XZu00000000XuZZZZZZZZuZZZZuZZuZZZ0`                   ',
    '                   .Jy0!       ..JwXl                                                       .<!_````````````_~<?7T4XZZZZZZZZuZu%                    ',
    '                  .yX=       .dyXY=!                                                       _`                      `_?7TXZZZZZZ!                    ',
    '                 .y0-.J&,   .yy$.....                                                     _`                            `~?4ZZC.__.__..             ',
    '                `dyyUY=!   .yyUUUUUUXXC                                                    _  ...._~~~~~__.....            `(=         `__.         ',
    '                 dZ) ..., .yy%                                                             ___(,......-gs..~~~~___~_..       _             _-       ',
    '                 dyyyXY7!.wyZyyyyyyX&                                                       ~_T5-____.-?:_~~:~~.....-_`__..  _               _.     ',
    '                 dy%     JZf`     ``                                                      _`   `_~~~_``       _~_~_~__     `_-.               __    ',
    '          ..((.. dyI+zlldy0<. ..(++++.                                                  _``                           __.      _.              _.   ',
    '          (lllttllllllllltllll<<<<<<<!                                                 _`                               __      _.              _   ',
    '            .lllllllllllllllllO+-``                                                    _.                                ~      .`              _   ',
    '           .tllltlltlllllllllllll:                                                      _.                               _      __              _   ',
    '           (llltllllltltlltlltlllO.                                                      _`                            ._         _             _`  ',
    '           lllllltllllllllllllllll~                                                     ._                            .`          ~            .`   ',
    '          .uyllllltlltlltlltlltlll!                                                      _                      ....-(_          `_ .(++++-. _`     ',
    '          ,M#lltlllllqNmllllllllll`                                                      _. `          ..     .(dZuZZZn-.        .(=======<<1       ',
    '         .JOOOlllltlldM8lltlltlzz<.                                                        `_-       .(J&J((JzXZZZZZZZZZXo_    .(==zsZ====<:+~      ',
    '        (ldppfIllllllllllllllz<~~~~                                                         .G----(J&NZZZZZZZZZZZZZuZZuZZZn-..(==uwZZk======v       ',
    '        .1lOOOlltlltlllltzz<~~~~~.~_                                                        JZZZZZXMMHZZZZZZZZuZZuZZZZZZu0VO===udZyZZyXAc<?`        ',
    '           ??<<<<<<<<?<<~~~~~.~.~~.~(z+(..........(.       -zz                        ` ..((z=======lzzzzzzzzzzzz==========zusXZyZZyZZyV            ',
    '                      ~~~.~.~~.~~~(zll=dyZyyZyyZyk=lltz-..Jll                      `..===1zuuwwwwwwwwwAAwsssssssOAwwwwwXZZZZZyZyZyZyZyX!            ',
    '                      _~.~~.~~~.(1llll=dZZZZZZZyZk=llllltz<~`                    `.(==uwZZyZZyZZZyZZyyZyZyZZZZyZyyZZZZZyZyyZyZZZyZZZyZ}             ',
    '                       ~~.~~._((llllll=zyyZyyZyZZ0========1......               `.==uXZZZyZZyZyZyZZyZZyZZyZyZyZZZyZyZZyZyZZyZyZyZyZyZf              ',
    '                         ~._-(llllllll==vVUUUUVVV1=llllllllv???<<<<1==l=++((....,==dZZZyZZyZZyZyZZyZZyZZyZZyZZyZyZZyyZyZZyZZyZyZZyZZf`              ',
    '                          .zlllllllltllllllllllllllllltllllz              `~!???==zZyZyZyZyZyZZZyZZyZZyZZyZZyZyZZyZZZyZyZZyZZyZZyZy0!               ',
  ],
  [
    '                                                                                                                                                    ',
    '                                                                                                       ..-uwZZZZZZZZZZZZXA+-..                      ',
    '                                                                                                   .(wZZZZZZZZuZuZZZZZZZZZZZZZZGJ-_```_.            ',
    '                                                                                                .(XZZZZZZZZZZZZZZZuZZZZZZZZZZZZZZV`     _           ',
    '                                                                                              .JZZZZZZZZZuZZuZZuZZZZZuZZZZZZZZZZr`_     _           ',
    '                                                                                             .XZu00000000XuZZZZZZZZuZZZZuZZuZZZ0` `....-            ',
    '                   .Jy0!       ..JwXl                                                       .<!_````````````_~<?7T4XZZZZZZZZuZu%                    ',
    '                  .yX=       .dyXY=!                                                       _`                      `_?7TXZZZZZZ!                    ',
    '                 .y0-.J&,   .yy$.....                                                     _`                            `~?4ZZC.__.__..             ',
    '                `dyyUY=!   .yyUUUUUUXXC                                                    _  ...._~~~~~__.....            `(=         `__.         ',
    '                 dZ) ..., .yy%                                                             ___(,......-gs..~~~~___~_..       _             _-       ',
    '                 dyyyXY7!.wyZyyyyyyX&                                                       ~_T5-____.-?:_~~:~~.....-_`__..  _               _.     ',
    '                 dy%     JZf`     ``                                                      _`   `_~~~_``       _~_~_~__     `_-.               __    ',
    '          ..((.. dyI+zlldy0<. ..(++++.                                                  _``                           __.      _.              _.   ',
    '          (lllttllllllllltllll<<<<<<<!                                                 _`                               __      _.              _   ',
    '            .lllllllllllllllllO+-``                                                    _.                                ~      .`              _   ',
    '           .tllltlltlllllllllllll:                                                      _.                               _      __              _   ',
    '           (llltllllltltlltlltlllO.                                                      _`                            ._         _             _`  ',
    '           lllllltllllllllllllllll~                                                     ._                            .`          ~            .`   ',
    '          .uyllllltlltlltlltlltlll!                                                      _                      ....-(_          `_ .(++++-. _`     ',
    '          ,M#lltlllllqNmllllllllll`                                                      _. `          ..     .(dZuZZZn-.        .(=======<<1       ',
    '         .JOOOlllltlldM8lltlltlzz<.                                                        `_-       .(J&J((JzXZZZZZZZZZXo_    .(==zsZ====<:+~      ',
    '        (ldppfIllllllllllllllz<~~~~                                                         .G----(J&NZZZZZZZZZZZZZuZZuZZZn-..(==uwZZk======v       ',
    '        .1lOOOlltlltlllltzz<~~~~~.~_                                                        JZZZZZXMMHZZZZZZZZuZZuZZZZZZu0VO===udZyZZyXAc<?`        ',
    '           ??<<<<<<<<?<<~~~~~.~.~~.~(z+(..........(.                                  ` ..((z=======lzzzzzzzzzzzz==========zusXZyZZyZZyV            ',
    '                      ~~~.~.~~.~~~(zll=dyZyyZyyZyk=lltz-..vlllz                    `..===1zuuwwwwwwwwwAAwsssssssOAwwwwwXZZZZZyZyZyZyZyX!            ',
    '                      _~.~~.~~~.(1llll=dZZZZZZZyZk=llllltz<~`                    `.(==uwZZyZZyZZZyZZyyZyZyZZZZyZyyZZZZZyZyyZyZZZyZZZyZ}             ',
    '                       ~~.~~._((llllll=zyyZyyZyZZ0========1......               `.==uXZZZyZZyZyZyZZyZZyZZyZyZyZZZyZyZZyZyZZyZyZyZyZyZf              ',
    '                         ~._-(llllllll==vVUUUUVVV1=llllllllv???<<<<1==l=++((....,==dZZZyZZyZZyZyZZyZZyZZyZZyZZyZyZZyyZyZZyZZyZyZZyZZf`              ',
    '                          .zlllllllltllllllllllllllllltllllz              `~!???==zZyZyZyZyZyZZZyZZyZZyZZyZZyZyZZyZZZyZyZZyZZyZZyZy0!               ',
  ],
]

$bottoms = [
  [
    '                         zzzwOtltlltllllllllllllllltllltlllz                   -==wyZyZZyZZyZyZyZyZyZyZyZyZyZyZyZZyZyZZyZyZyZZyZZyZ>                ',
    '                         vzZ77?lllllzzllllllllltOOOOlllltlll-                  (=zZZyZZyZyZZyZyZZyZZyZZyZZyZZZyZyZyZZyZZyZZyZyZyZ0^                 ',
    '                         (zzZ` lltl!        ?7Ovzvzz;?1llllll-        ..((-.     ?7TUXZZyZyZZyZZyZyZZyZZyZZyZyZZZyZyZyZyZZyZZyXY=                   ',
    '                         .zvwlll:.              _Cvvv-   ??1llO      ,======1             ===v                          1==1.                       ',
    '                          j.:ll>                   .wzZ   .zlO.      ====<<<!            (===!                          .===>                       ',
    '                        _l`+l`                       Oz2  .ll:       <====+-.............===<............................+===-.......(1==-          ',
    '                       `jt.wx{                       Jvv! .ll:        ?1===============================================================?z!          ',
    '                           v(C:                      (CC> ?<<`           _??<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<?!`            ',
    '                                                                                                                                                    ',
  ],
  [
    '                         .zzwOtltlltllllllllllllllltllltlllz                   -==wyZyZZyZZyZyZyZyZyZyZyZyZyZyZyZZyZyZZyZyZyZZyZZyZ>                ',
    '                         vzzz77?lllllzzllllllllltOOOOlllltlll-                 (=zZZyZZyZyZZyZyZZyZZyZZyZZyZZZyZyZyZZyZZyZZyZyZyZ0^                 ',
    '                        .wvvz   lltl!        ?7Ovzvzz;?1llllll-       ..((-.     ?7TUXZZyZyZZyZZyZyZZyZZyZZyZyZZZyZyZyZyZZyZZyXY=                   ',
    '                       (zzZ`    lll:             _Cvvv-   ??1llO-    ,======1             ===v                          1==1.                       ',
    '                        .zvw.   ll>j               .wzZ    .zlO.     ====<<<!            (===!                          .===>                       ',
    '                          wzz{ +lvj                 Oz2     .ll:     <====+-.............===<............................+===-.......(1==-          ',
    '                          `vC  .lt{                Jvv!    .ll:       ?1===============================================================?z!          ',
    '                              l`v                  (CC>    ?<<`          _??<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<?!`            ',
    '                                                                                                                                                    ',
  ],
  [
    '                         .zzwOtltlltllllllllllllllltllltlllz                   -==wyZyZZyZZyZyZyZyZyZyZyZyZyZyZyZZyZyZZyZyZyZZyZZyZ>                ',
    '                         vzzz77?lllllzzllllllllltOOOOlllltlll-                 (=zZZyZZyZyZZyZyZZyZZyZZyZZyZZZyZyZyZZyZZyZZyZyZyZ0^                 ',
    '                        .wvvz   lltl!        ?7Ovzvzz;?1llllll-       ..((-.     ?7TUXZZyZyZZyZZyZyZZyZZyZZyZyZZZyZyZyZyZZyZZyXY=                   ',
    '                        zzZ`    .lll           _Cvvv-     ??1ll:     ,======1             ===v                          1==1.                       ',
    '                       .zvw.     ll>j           .wzZ        .zlO.    ====<<<!            (===!                          .===>                       ',
    '                       wzz`      llv`            Oz2         ?ll:    <====+-.............===<............................+===-.......(1==-          ',
    '                      lvC         .lt{           Jvv!         .ll:    ?1===============================================================?z!          ',
    '                                   l`v           CC>:         ?<<`       _??<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<?!`            ',
    '                                                                                                                                                    ',
  ],
  [
    '                         .zzwOtltlltllllllllllllllltllltlllz                   -==wyZyZZyZZyZyZyZyZyZyZyZyZyZyZyZZyZyZZyZyZyZZyZZyZ>                ',
    '                         vzzz77?lllllzzllllllllltOOOOlllltlll-                 (=zZZyZZyZyZZyZyZZyZZyZZyZZyZZZyZyZyZZyZZyZZyZyZyZ0^                 ',
    '                        .wvvz   lltl!        ?7Ovzvzz;?1llllll-       ..((-.     ?7TUXZZyZyZZyZZyZyZZyZZyZZyZyZZZyZyZyZyZZyZZyXY=                   ',
    '                        zzZ`   .lll              _Cvvv-   ??1llO-    ,======1             ===v                          1==1.                       ',
    '                        .zvl. (l>j                 .wzZ    .zlO.     ====<<<!            (===!                          .===>                       ',
    '                         wzz`  llv`                 Oz2     .ll:     <====+-.............===<............................+===-.......(1==-          ',
    '                         wzz    .lt{                Jvv!   .ll:       ?1===============================================================?z!          ',
    '                         lvC     `vl                (CC>   ?<<`          _??<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<?!`            ',
    '                                                                                                                                                    ',
  ],
]
